config/routes.rb
require 'subscribem/constraints/subdomain_required'

Subscribem::Engine.routes.draw do

  constraints(Subscribem::Constraints::SubdomainRequired) do
    scope :module => "account" do
      root :to => "dashboard#index", :as => :account_root
      # get "/sign_in", :to => "sessions#new"
      # post "/sign_in", :to => "sessions#create", :as => :sessions
      get "/sign_up", :to => "users#new", :as => :user_sign_up
      post "/sign_up", :to => "users#create", :as => :do_user_sign_up
    end
  end

  root 'welcome#index'

  devise_for :users, class_name: 'Subscribem::User', module: :devise

  get '/sign_up', :to => 'accounts#new', :as => :sign_up
  resources :accounts, only: [:create, :index, :new]
end

app/views/shared/_flash.html.slim
.container
  .alert.alert-dismissible role="alert" class="alert-warning hidden alert-please-update"
    button.close aria-label="Close" data-dismiss="alert" type="button" 
      span aria-hidden="true"  ×
    strong Please update
    | Despite the fact that the record doens't show on your screen you must save it to delete it!

  - flash.each do |k,v|
    .alert.alert-dismissible role="alert" class="#{alert_class(k)}"
      button.close aria-label="Close" data-dismiss="alert" type="button" 
        span aria-hidden="true"  ×
      strong 
      = v

app/views/shared/_header.html.slim
.navbar.navbar-default.navbar-fixed-top
  .container
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      =link_to 'The main app', account_root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li.dropdown
            a.dropdown-toggle aria-expanded="false" data-toggle="dropdown" href="#" role="button" 
              | Settings
              span.caret
            ul.dropdown-menu role="menu" 
              li
              | Signed in as #{current_user.email}
              li.divider
              li
                =link_to 'Log out', destroy_user_session_path, method: :delete